use anyhow::Context;
use clap::Parser;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

mod action;
mod app;
mod cli;
mod components;
mod config;
mod errors;
mod layout;
mod stats;
mod theme;
mod tui;

fn main() -> anyhow::Result<()> {
    let args = cli::Args::parse();

    // Log to a file so tracing output doesn't corrupt the TUI.
    let log_dir = dirs::data_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join("toppers");
    std::fs::create_dir_all(&log_dir).context("creating log dir")?;
    let log_file =
        std::fs::File::create(log_dir.join("toppers.log")).context("creating log file")?;
    let level = match args.verbose {
        0 => tracing::Level::WARN,
        1 => tracing::Level::INFO,
        _ => tracing::Level::DEBUG,
    };
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer().with_writer(log_file))
        .with(tracing_subscriber::filter::LevelFilter::from_level(level))
        .init();

    if args.init_config {
        print!("{}", DEFAULT_CONFIG_TEMPLATE);
        return Ok(());
    }

    let mut cfg = config::Config::load(args.config.as_deref()).context("loading config")?;
    apply_cli_overrides(&mut cfg, &args);

    let rt = tokio::runtime::Runtime::new().context("creating tokio runtime")?;
    rt.block_on(async {
        let mut app = app::App::new(cfg, args.debug).context("creating App")?;
        app.run().await.context("running App")
    })
}

fn apply_cli_overrides(cfg: &mut config::Config, args: &cli::Args) {
    if let Some(t) = &args.theme
        && let Ok(theme) = t.parse()
    {
        cfg.general.theme = theme;
    }
    if let Some(r) = &args.refresh_rate
        && let Ok(d) = humantime::parse_duration(r)
    {
        cfg.general.refresh_rate_ms = d.as_millis() as u64;
    }
    if let Some(p) = &args.preset {
        cfg.layout.preset = p.clone();
    }
    if let Some(pos) = &args.status_bar {
        cfg.layout.status_bar = pos.clone();
    }
    // --hide wins over --show
    if let Some(show) = &args.show {
        cfg.layout.show = show.clone();
    }
    if let Some(hide) = &args.hide {
        cfg.layout.show.retain(|c| !hide.contains(c));
    }
}

const DEFAULT_CONFIG_TEMPLATE: &str = r#"# toppers default configuration
# Generated by: toppers --init-config
# All options are commented out — uncomment and edit as needed.

[general]
# Refresh interval for all components. Examples: "500ms", "1s", "2s"
# refresh_rate = "1s"

# Color theme. "auto" detects light/dark from terminal background.
# theme = "auto"   # "auto" | "light" | "dark"

# Bounded action channel capacity.
# channel_capacity = 128

[layout]
# Base layout preset.
# preset = "sidebar"   # "sidebar" | "classic" | "dashboard"

# Status bar position.
# status_bar = "top"   # "top" | "bottom" | "hidden"

# Which components to show (omit to hide).
# show = ["cpu", "mem", "net", "disk", "process"]

# Slot overrides — replace default component in a named slot.
# Sidebar slots: left_top, left_mid, left_bot, right
# Classic slots: top_left, top_right_top, top_right_bot, bottom
# Dashboard slots: top, mid_left, mid_right, bottom
# left_top = "cpu"

[process]
# Default sort column: "cpu" | "mem" | "pid" | "name"
# default_sort = "cpu"
# default_sort_dir = "desc"   # "asc" | "desc"
# show_tree = false

[keybindings]
# focus_proc = "p"
# focus_cpu  = "c"
# focus_mem  = "m"
# focus_net  = "n"
# focus_disk = "i"
# fullscreen = "f"
# help       = "?"
# debug      = "`"
"#;
